# Generated by Django 4.1 on 2022-10-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_ipaddress_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
