# Generated by Django 4.1 on 2022-12-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_article_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="tags",
        ),
    ]
